### ISSUE TITLE
Should vmOpsTool execute networkDiscovery by vm name?

### ISSUE THREAD

**Issue by nphmuller** [Microsoft/vsts-vmware#66]
In vmOpsTool:VMWareImpl.java many methods run the waitForVMToBeDeployReady method. This method finally checks if the vm is fully up, by trying to resolve the dns name and/or netbios name. 

I however don't really understand how this would work, since it tries to resolve both by vm name. Is it really that common for the vm name to be the dns and/or netbios name? Because when it isn't, the method keeps polling for the max build time (about 20~30 minutes in my case).

This really doesn't seem optimal to me. But it can be solved in one of the following way's:
-Add a checkbox to the task ui, which indicates if the task should wait for the vm to be deploy ready (or at least network discovered). This makes the waiting optional.
-Added a textfield for the dnsname/netbiosname/ip-address, which is used to poll if the vm is up.

What do you think of the proposed solutions? Do you have any better solutions?
I'm willing to implement the solution and create a PR. Can't promise when, though.

**Comment by mvvsubbu** [comment]
there is a parameter in UI saying WaitTime, you can set that to zero so that it will not wait for this step.

**Comment by nphmuller** [comment]
Ah, that's more than good enough for me. Closing this issue.

**Comment by mvvsubbu** [comment]
Thank you
